services:
  database:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=dev
    ports:
      - "5434:5432"
    networks:
      - dev
  url-shortener:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
      - "80:80"
    networks:
      - dev
    volumes:
      - .:/app
      - /app/obj/ # <- directory won't be mounted
      - /app/bin/ # <- directory won't be mounted
      - /app/HotReload.Sample.API/obj/ # <- directory won't be mounted
      - /app/HotReload.Sample.API/bin/ # <- directory won't be mounted
      - ~/.aspnet/https:/https:ro
    build:
      context: .
      dockerfile: dev.Dockerfile
    depends_on:
      - database
  angular:
    build:
      context: URL-Shortener.client
      dockerfile: dev.Dockerfile
    networks:
      - dev
    ports:
      - '4200:4200'
    volumes:
      - ./URL-Shortener.client/src:/app/src
networks:
  dev:
    driver: bridge
