services:
  database:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=dev
    ports:
      - "5434:5432"
    networks:
      - dev
  url-shortener:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
      - "80:80"
    networks:
      - dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    depends_on:
      - database
networks:
  dev:
    driver: bridge
